//Maya Preference 2026 (Release 1)
//
//

//
// The hotkey set
//
hotkeySet -source "Maya_Default" -current Maya_Default_Duplicate;
//
// The hotkey contexts and hotkeys
//
hotkey -keyShortcut "F3" -name ("");
hotkey -keyShortcut "F4" -name ("");
hotkey -keyShortcut "c" -ctl -name ("CenterPivotNameCommand");
hotkey -keyShortcut "F2" -name ("");
hotkey -keyShortcut "F6" -name ("");
hotkey -keyShortcut "F5" -name ("");
hotkeyCtx -type "Editor" -addClient "posePanel";
hotkeyCtx -type "Editor" -addClient "dopeSheetPanel";
hotkeyCtx -type "Editor" -addClient "shapePanel";
hotkeyCtx -type "Editor" -addClient "nodeEditorPanel";
hotkeyCtx -type "Editor" -addClient "motionMakerEditor";
hotkeyCtx -type "Editor" -addClient "graphEditor";
hotkeyCtx -type "Editor" -addClient "renderWindowPanel";
hotkeyCtx -type "Editor" -addClient "hyperShadePanel";
hotkeyCtx -type "Editor" -addClient "timeEditorPanel";
hotkeyCtx -type "Editor" -addClient "profilerPanel";
hotkeyCtx -type "Editor" -addClient "hyperGraphPanel";
hotkeyCtx -type "Editor" -addClient "polyTexturePlacementPanel";
hotkeyCtx -type "Editor" -addClient "outlinerPanel";
hotkeyCtx -type "Tool" -addClient "xgmIGBrush";
hotkeyCtx -type "Tool" -addClient "texSculptCacheContext";
hotkeyCtx -type "Tool" -addClient "Unfold3DBrush";
hotkeyCtx -type "Tool" -addClient "sculptMeshCache";
hotkeyCtx -type "Tool" -addClient "bpDraw";
hotkeyCtx -type "Tool" -addClient "texCutContext";
hotkeyCtx -type "Tool" -addClient "polyCutUV";
hotkeyCtx -type "Tool" -addClient "SymmetrizeUVBrush";
